#!/bin/sh

readonly PROJECT_ROOT_DIR=$(git rev-parse --show-toplevel)
readonly COMMANDS_DIR="$PROJECT_ROOT_DIR/aqua/extensions/commands"

cd "$COMMANDS_DIR"
files_to_analyze=$(ls | grep ".*\.py" | grep -v '__init__.py')
for file in $files_to_analyze
do
    command_name=$(echo "$file" | cut -f 1 -d '.')
    if [[ $(cat "$file" | grep @authorize | wc -l) == 0 ]]
    then
        echo "Pre-commit hook failed: $file is not using authorize."
        exit 1
    else
        authorize_line=$(cat "$file" | grep -n @authorize | cut -d ':' -f 1)
        command_line=$(cat "$file" | grep -n "def $command_name" | cut -d ':' -f 1)
        if [[ "$command_line" != $(( "$authorize_line" + 1 )) ]]
        then
            echo $command_line
            echo "Pre-commit hook failed: $file is using a misplaced authorize."
            exit 1
        fi
    fi
done
