name: Bandit check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Perform security check
      uses: jpetrucciani/bandit-check@master
      with:
        path: './aqua'
