# This workflow will install Python dependencies and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -Iv mypy==0.812
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Lint with mypy
      run: |
        mypy .
    - name: Run tests
      run: |
        pytest
