# This script ensures the code passes pre-commit hook.

name: Pre-commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run pre-commit script
      run: |
        bash ./hooks/pre-commit
